[tool.poetry]
name = "palette_generator"
version = "0.1.0"
description = ""
authors = ["neonfuzz"]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
matplotlib = "@latest"
numpy = "@latest"
pandas = "@latest"
scipy = "^1.7.3"
Wand = "@latest"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
